# These are supported funding model platforms

github: [ClassicUA]
custom: ['send.monobank.ua/6T3jNinoyF','mobile-app.pumb.ua/T6swC9g13dnTQnGN7' 'https://www.paypal.com/donate/?hosted_button_id=RUVLFNJFTWQ6C']
#Bitcoin: 33d133tnqEuPztCRoHsncnRQdXuo5eJ6xf
