# These are supported funding model platforms

github: [ClassicUA]
custom: ['send.monobank.ua/6T3jNinoyF','https://www.paypal.com/donate/?hosted_button_id=RUVLFNJFTWQ6C']
#Bitcoin: 33d133tnqEuPztCRoHsncnRQdXuo5eJ6xf
